name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: Docker Compose Action
      uses: isbang/compose-action@v1.0.0
      with:
        compose-file: ./docker-compose.yml
    
    - name: Test
      run: go test -race -covermode=atomic -coverprofile="profile.cov" ./...
      
    - name: actions-goveralls
      # You may pin to the exact commit or the version.
      # uses: shogo82148/actions-goveralls@31ee804b8576ae49f6dc3caa22591bc5080e7920
      uses: shogo82148/actions-goveralls@v1.6.0
      with:
        # a path to your cover profile.
        path-to-profile: profile.cov 
      
      
      
