name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: Docker Compose Action
    # You may pin to the exact commit or the version.
    # uses: isbang/compose-action@fab6f72bef82b75de541a7b9da1d23412953c2bd
      uses: isbang/compose-action@v1.0.0
      with:
        # relative path to compose file
        compose-file: ./docker-compose.yml
    
    - name: Test
      run: go test -v ./... -covermode=atomic -coverprofile=coverage.out -coverpkg=./... -count=1
      
    - name: Go Coverage Badge
      # You may pin to the exact commit or the version.
      # uses: tj-actions/coverage-badge-go@57e0c6b82e0bf6b0d486c4d8df22a51067f26fb7
      uses: tj-actions/coverage-badge-go@v1.2
      with:
        # File containing the tests output
        filename: coverage.out
        # Color of the badge - green/yellow/red
        color: green
        # At what percentage does the badge become green instead of yellow (default: 70)
        green: 80
        # Target file (default "README.md")
        target: ./README.md
        # Text on the left side of the badge (default: "Coverage")
        text: Coverage
        # Text on the right side of the badge
        value: test
        # At what percentage does the badge become yellow instead of red (default 30)
        yellow: 50
